sudo: required
language: 
    - c

compiler: gcc

branches: # safelist
    only:
    - develop

os:
    - linux

install:
    - gem install bundler
    - gem install ceedling
    - apt-get install lcov
    - apt-get install cppcheck

script:
    - cd tools/ceedling && sudo ./test-all.sh
    - cd ../analyzer && sudo ./cppcheck.sh
    - ./uno-install.sh
    - ./uno.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
