sudo: required
language: 
    - c

compiler: gcc

branches: # safelist
    only:
    - develop

os:
    - linux

before_install:
- rvm install 2.4.0

install:
    - sudo gem install ceedling
    - sudo apt-get install lcov
    - sudo apt-get install cppcheck

script:
    - cd tools/ceedling && sudo ./test-all.sh
    - cd ../analyzer && sudo ./cppcheck.sh
    - ./uno-install.sh
    - ./uno.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
