name: Ceedling tests

on:
    push:
        branch:
        - issue-workflows

env:
    DOCKER_USER: leanfrancucci
    DOCKER_REPO: ceedling
    DOCKER_TAG: latest

jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Run Ceedling tests
          uses: docker://${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
          with:
            entrypoint: ls
#           entrypoint: /bin/echo
#           args: /bin/bash -c "cd tools/ceedling; ./test-all.sh"
