name: Ceedling tests

on:
    push:
        branch:
        - issue-workflows

env:
    DOCKER_USER: leanfrancucci
    DOCKER_REPO: ceedling

jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
        - run: echo 1: ${DOCKER_USER} 2: $DOCKER_REPO 3: ${{ env.DOCKER_USER }}
#       - uses: actions/checkout@v2
#       - name: Run Ceedling tests
#         uses: docker://$DOCKER_USER/$DOCKER_REPO:latest
#         with:
#           entrypoint: ls
#           entrypoint: /bin/echo
#           args: /bin/bash -c "cd tools/ceedling; ./test-all.sh"
