name: Ceedling tests

on:
    push:
        branch:
        - issue-workflows

env:
    DOCKER_USER: leanfrancucci
    DOCKER_REPO: ceedling

jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
        - run: echo ${DOCKER_USER} $DOCKER_REPO
#       - uses: actions/checkout@v2
    DOCKER_TAG: latest

#       - name: Run Ceedling tests
#         uses: docker://$DOCKER_USER/$DOCKER_REPO:$DOCKER_TAG
#         with:
#           entrypoint: ls
#           entrypoint: /bin/echo
#           args: /bin/bash -c "cd tools/ceedling; ./test-all.sh"
