name: Ceedling tests

on:
    push:
        branch:
        - issue-workflows

env:
    DOCKER_USER: leanfrancucci
    DOCKER_REPO: ceedling

jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Ceedling tests
          uses: docker://docker.io/leanfrancucci/ceedling:latest
          with:
            entrypoint: /bin/bash
            args: -c "cd tools/ceedling; ./test-all.sh"
