name: Static code analysis

on:
    push:
        branch:
        - issue-workflows
        path:
        - '.github/workflows/static-analyzer.yml'
        - 'source/fwk/**'
        - 'source/mempool/**'
        - 'source/queue/**'
        - 'source/sm/**'
        - 'source/sma/**'
        - 'source/tmr/**'
        - 'source/trc/**'

jobs:
    code-analysis:
        runs-on: ubuntu-latest
        container:
            image: leanfrancucci/ceedling:latest
        steps:
        - uses: actions/checkout@v1
          with:
            submodules: recursive
        - name: Execute Cppcheck analyzer
          working-directory: tools/analyzer
          run: ./cppcheck.sh cppcheck-report.xml
          continue-on-error: true
        - name: Check errors
          if: ${{ failure() }}
          uses: actions/upload-artifact@master
          continue-on-error: True
          with:
            name: cppcheck-report.xml
            path: cppcheck-report.xml
          run: exit 1
